# Generated by Django 4.0.3 on 2022-04-09 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='interview',
            options={'verbose_name': 'Собеседование', 'verbose_name_plural': 'Собеседования'},
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='responses',
            field=models.ManyToManyField(blank=True, to='api.candidate', verbose_name='Отклики'),
        ),
    ]
